import type { Rule } from '../types.js';

export const aiTellRules: Rule[] = [
  {
    id: 'no-obvious-comments',
    name: 'No Obvious Comments',
    description: 'Comments that restate what the code does are noise. AI generates these constantly.',
    category: 'ai-tell',
    severity: 'info',
    languages: ['js', 'ts', 'jsx', 'tsx', 'mjs', 'cjs'],
    pattern: /\/\/\s*(?:increment|decrement|initialize|declare|define|create|set|get|return|check|loop|iterate|import|require|export|assign|call|invoke|update|fetch|retrieve|store|save|log|print|handle|process)\s+(?:the\s+)?(?:a\s+)?\w+\s*$/i,
    antiPattern: /eslint-disable|@ts-|@type|@param|@returns|jsdoc|TODO|FIXME|NOTE|HACK|BUG|WARN/i,
    messageTemplate: 'Comment restates what the code does. Remove it or explain WHY instead.',
  },
  {
    id: 'no-ts-any',
    name: 'No TypeScript any',
    description: '`as any` and `: any` bypass the type system. AI uses these to silence type errors.',
    category: 'ai-tell',
    severity: 'warn',
    languages: ['ts', 'tsx'],
    pattern: /:\s*any\b|as\s+any\b|<any\s*>/,
    antiPattern: /eslint-disable|@ts-expect-error|@ts-ignore|\/\/\s*safe/,
    messageTemplate: 'TypeScript `any` type bypasses type safety. Use a specific type.',
  },
  {
    id: 'no-hedging-comments',
    name: 'No Hedging Comments',
    description: 'AI writes uncertain comments like "should work" or "might not be the best approach".',
    category: 'ai-tell',
    severity: 'info',
    languages: ['js', 'ts', 'jsx', 'tsx', 'mjs', 'cjs', 'py'],
    pattern: /(?:\/\/|#)\s*.*(?:should\s+work|might\s+not|hopefully|not\s+sure\s+if|probably\s+(?:not\s+)?(?:the\s+)?(?:best|right|correct)|replace\s+this\s+with\s+your\s+actual|this\s+(?:may|might|could)\s+(?:need|require)|i'?m\s+not\s+(?:sure|certain))\b/i,
    antiPattern: /eslint-disable|@ts-|noqa/,
    messageTemplate: 'Hedging comment detected. Either fix the uncertainty or remove the comment.',
  },
  {
    id: 'no-step-comments',
    name: 'No Step-by-Step Comments',
    description: 'AI generates numbered step comments like "Step 1: Initialize" that add noise.',
    category: 'ai-tell',
    severity: 'info',
    languages: ['js', 'ts', 'jsx', 'tsx', 'mjs', 'cjs', 'py'],
    pattern: /(?:\/\/|#)\s*(?:step\s+\d+\s*[:.-])/i,
    antiPattern: /eslint-disable|noqa|README|\.md$/,
    messageTemplate: 'Numbered step comment. Let the code speak for itself.',
  },
  {
    id: 'no-section-dividers',
    name: 'No Section Divider Comments',
    description: 'AI generates ASCII section dividers like "// ========" that clutter code.',
    category: 'ai-tell',
    severity: 'info',
    languages: ['js', 'ts', 'jsx', 'tsx', 'mjs', 'cjs', 'py'],
    pattern: /(?:\/\/|#)\s*[-=*~]{6,}/,
    antiPattern: /eslint-disable|noqa|license|copyright/i,
    messageTemplate: 'ASCII section divider. Use code organization (modules, classes) instead.',
  },
  {
    id: 'no-stub-function',
    name: 'No Stub Functions',
    description: 'AI scaffolding that ships to production: throw "not implemented", return null, etc.',
    category: 'ai-tell',
    severity: 'warn',
    languages: ['js', 'ts', 'jsx', 'tsx', 'mjs', 'cjs'],
    pattern: /throw\s+new\s+Error\s*\(\s*['"](?:not\s+implemented|todo|implement\s+this|implement\s+me|stub|fixme|placeholder)['"]\s*\)/i,
    antiPattern: /eslint-disable|abstract|interface|test|spec|mock/i,
    messageTemplate: 'Stub function detected. Implement it or remove it.',
  },
  {
    id: 'no-narrator-comments',
    name: 'No Narrator Comments',
    description: 'AI writes "This function handles..." style comments that narrate instead of explain.',
    category: 'ai-tell',
    severity: 'info',
    languages: ['js', 'ts', 'jsx', 'tsx', 'mjs', 'cjs', 'py'],
    pattern: /(?:\/\/|#)\s*(?:this\s+(?:function|method|class|module|component|hook|helper|utility)\s+(?:is\s+(?:used\s+)?(?:to|for)|handles?|creates?|returns?|processes?|manages?|implements?|provides?|performs?|does))\b/i,
    antiPattern: /eslint-disable|@param|@returns|jsdoc|noqa|docstring/i,
    messageTemplate: 'Narrating what the function does. The name should be self-explanatory.',
  },
];
