import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { scan } from '../src/scanner.js';
import { applyFixes, isFixable } from '../src/fixer.js';
import { loadConfig } from '../src/config.js';
import type { Finding } from '../src/types.js';

const SAMPLE = [
  'function add(a: number, b: number) {',
  '  return a + b;',
  '}',
  '// Generated by ChatGPT',
  'const total = add(1, 2);',
  '// Co-Authored-By: Claude',
  'const user = value as unknown as User;',
  '',
].join('\n');

describe('fixer', () => {
  let dir: string;
  let file: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'vibecheck-fixer-'));
    file = join(dir, 'sample.ts');
    writeFileSync(file, SAMPLE);
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('removes ai attribution comment lines and leaves code intact', async () => {
    const config = loadConfig();
    const before = await scan(dir, config);
    const attribution = before.findings.filter((f) => f.rule === 'no-ai-attribution');
    expect(attribution.length).toBe(2);

    const result = applyFixes(before.findings, dir);
    expect(result.filesModified).toBe(1);
    expect(result.linesRemoved).toBe(2);

    const content = readFileSync(file, 'utf-8');
    expect(content).not.toContain('Generated by ChatGPT');
    expect(content).not.toContain('Co-Authored-By: Claude');
    expect(content).toContain('function add(a: number, b: number) {');
    expect(content).toContain('const total = add(1, 2);');
    expect(content).toContain('const user = value as unknown as User;');
  });

  it('is idempotent: re-scan after fix reports no attribution findings', async () => {
    const config = loadConfig();
    const before = await scan(dir, config);
    applyFixes(before.findings, dir);

    const after = await scan(dir, config);
    expect(after.findings.filter((f) => f.rule === 'no-ai-attribution').length).toBe(0);

    const second = applyFixes(after.findings, dir);
    expect(second.linesRemoved).toBe(0);
    expect(second.filesModified).toBe(0);
  });

  it('does not touch non-fixable findings', async () => {
    const config = loadConfig();
    const before = await scan(dir, config);
    const doubleAssertion = before.findings.find((f) => f.rule === 'no-double-assertion');
    expect(doubleAssertion).toBeDefined();
    expect(isFixable(doubleAssertion as Finding)).toBe(false);

    applyFixes(before.findings, dir);
    const content = readFileSync(file, 'utf-8');
    expect(content).toContain('as unknown as User');
  });

  it('skips stale findings whose line content no longer matches', () => {
    const stale: Finding = {
      rule: 'no-ai-attribution',
      severity: 'warn',
      category: 'code-quality',
      file: 'sample.ts',
      line: 1,
      column: 1,
      message: 'stale',
      snippet: '// Generated by ChatGPT',
    };

    const result = applyFixes([stale], dir);
    expect(result.linesRemoved).toBe(0);
    expect(result.filesModified).toBe(0);
    expect(readFileSync(file, 'utf-8')).toContain('function add');
  });
});
